from enum import Enum

class AppointmentStatus(str, Enum):

    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELED_BY_PATIENT = "CANCELED_BY_PATIENT"
    CANCELED_BY_DOCTOR = "CANCELED_BY_DOCTOR"
    CANCELED_BY_ADMIN = "CANCELED_BY_ADMIN"